"""
Simulator export module for generating CMG compatible input files.
Provides functionality to export optimized EOR parameters to commercial reservoir simulators.
"""

import logging
from typing import Dict, Any, List, Optional
import datetime
from dataclasses import dataclass

logger = logging.getLogger(__name__)

@dataclass
class SimulatorExportConfig:
    """Configuration for simulator export options."""
    include_comments: bool = True
    use_si_units: bool = False
    date_format: str = "DD/MM/YYYY"
    max_line_length: int = 80

class SimulatorExporter:
    """
    Exports optimized EOR parameters to CMG simulator format.
    Generates keyword files compatible with commercial reservoir simulators.
    """

    def __init__(self, config: Optional[SimulatorExportConfig] = None):
        self.config = config or SimulatorExportConfig()

    def export_to_cmg(self, results: Dict[str, Any], filename: str) -> bool:
        """
        Export optimized parameters to CMG GEM/STARS format.
        
        Args:
            results: Optimization results dictionary from OptimizationEngine
            filename: Output filename for CMG keyword file
            
        Returns:
            bool: True if export successful, False otherwise
        """
        try:
            with open(filename, 'w') as f:
                self._write_cmg_header(f, results)
                self._write_cmg_injection_section(f, results)
                self._write_cmg_well_controls(f, results)
                self._write_cmg_fluid_properties(f, results)
                self._write_cmg_schedule(f, results)
                
            logger.info(f"CMG export successful: {filename}")
            return True
            
        except Exception as e:
            logger.error(f"CMG export failed: {e}")
            return False

    def _write_cmg_header(self, f, results: Dict[str, Any]):
        """Write CMG file header with comments and metadata."""
        if self.config.include_comments:
            f.write("!-- CMG Keyword File Generated by CO2EOR Optimizer --!\n")
            f.write(f"!-- Generated: {datetime.datetime.now().isoformat()} --!\n")
            f.write("!-- Software: CO2EOR Optimization Suite --!\n\n")
        
        f.write("TITLE 'CO2 EOR Optimization Results'\n")
        f.write("UNIT SI\n" if self.config.use_si_units else "UNIT FIELD\n")
        f.write("\n")
    
    def _write_cmg_injection_section(self, f, results: Dict[str, Any]):
        """Write CMG injection section with optimized parameters."""
        params = results.get('optimized_params_final_clipped', {})
        profiles = results.get('optimized_profiles', {})
        
        if self.config.include_comments:
            f.write("!-- Injection Parameters --!\n")
        
        f.write("INJECTION\n")
        f.write("INJECTOR 'INJ1' FLOW STB\n")
        f.write(f"  RATE {params.get('rate', 5000.0):.1f}\n")
        f.write(f"  BHP {params.get('pressure', 3000.0):.1f}\n")
        
        if params.get('WAG_ratio'):
            f.write(f"  WAG {params.get('WAG_ratio', 1.0):.2f}\n")
        
        f.write("/\n\n")
    
    def _write_cmg_well_controls(self, f, results: Dict[str, Any]):
        """Write CMG well controls and completions."""
        if self.config.include_comments:
            f.write("!-- Well Controls and Completions --!\n")
        
        f.write("WELL 'INJ1' OPEN SIMULTANEOUS SIM-SEP\n")
        f.write("  PERF GEO 'INJ1'\n")
        f.write("  METHOD 2\n")
        f.write("/\n\n")
    
    def _write_cmg_fluid_properties(self, f, results: Dict[str, Any]):
        """Write CMG fluid properties section."""
        if self.config.include_comments:
            f.write("!-- Fluid Properties --!\n")
        
        f.write("FLUIDPROP\n")
        f.write("  COMPONENT 'CO2' MOLWT 44.01 CRITICAL 72.8 1071.0\n")
        f.write("  COMPONENT 'C1' MOLWT 16.04 CRITICAL 45.4 673.1\n")
        f.write("  BINARY 0.1000 0.0 0.0 0.0 0.0 0.0\n")
        f.write("/\n\n")
    
    def _write_cmg_schedule(self, f, results: Dict[str, Any]):
        """Write CMG schedule section based on optimized profiles."""
        profiles = results.get('optimized_profiles', {})
        eor_params = results.get('eor_parameters', {})
        op_params = results.get('operational_parameters', {})
        if not profiles or not eor_params or not op_params:
            return
            
        if self.config.include_comments:
            f.write("!-- Injection Schedule --!\n")
        
        start_date = getattr(op_params, 'start_date', datetime.date(2025, 1, 1))
        
        f.write("SCHEDULE\n")
        f.write(f"  DATE {start_date.strftime('%d/%m/%Y')}\n")

        injection_scheme = getattr(eor_params, 'injection_scheme', 'continuous')
        resolution = getattr(op_params, 'time_resolution', 'annual')
        num_steps = len(profiles.get(f'{resolution}_oil_stb', []))

        if injection_scheme == 'continuous':
            f.write("  !-- Continuous Injection Schedule --!\n")
            rates = profiles.get(f'{resolution}_co2_injected_mscf', [])
            if rates:
                for i in range(num_steps):
                    rate = rates[i]
                    f.write(f"  DATE {start_date.year + i}/01/01\n") # Assuming annual for now
                    f.write(f"  INJECTOR 'INJ1' RATE {rate:.1f} BHP {results.get('optimized_params_final_clipped', {}).get('pressure', 3000.0):.1f}\n")
        elif injection_scheme == 'wag':
            f.write("  !-- WAG Injection Schedule (Not Yet Implemented) --!\n")

        f.write("/\n\n")

    def generate_summary_report(self, results: Dict[str, Any], format: str = "csv") -> str:
        """
        Generate standardized summary report in various formats.
        
        Args:
            results: Optimization results dictionary
            format: Output format ('csv', 'json', 'text')
            
        Returns:
            str: Formatted report content
        """
        if format == "csv":
            return self._generate_csv_report(results)
        elif format == "json":
            return self._generate_json_report(results)
        else:
            return self._generate_text_report(results)
    
    def _generate_csv_report(self, results: Dict[str, Any]) -> str:
        """Generate CSV format summary report."""
        params = results.get('optimized_params_final_clipped', {})
        metrics = results.get('final_metrics', {})
        
        csv_lines = [
            "Parameter,Value,Units",
            f"Injection Rate,{params.get('rate', 0):.1f},STB/day",
            f"Injection Pressure,{params.get('pressure', 0):.1f},psi",
            f"WAG Ratio,{params.get('WAG_ratio', 1.0):.2f},-",
            f"Recovery Factor,{metrics.get('recovery_factor', 0):.4f},fraction",
            f"NPV,{metrics.get('npv', 0):.0f},USD",
            f"CO2 Utilization,{metrics.get('co2_utilization', 0):.2f},MSCF/STB"
        ]
        
        return "\n".join(csv_lines)
    
    def _generate_json_report(self, results: Dict[str, Any]) -> str:
        """Generate JSON format summary report."""
        import json
        return json.dumps(results, indent=2, default=str)
    
    def _generate_text_report(self, results: Dict[str, Any]) -> str:
        """Generate text format summary report."""
        params = results.get('optimized_params_final_clipped', {})
        metrics = results.get('final_metrics', {})
        
        report = [
            "CO2 EOR Optimization Results Summary",
            "====================================",
            f"Injection Rate: {params.get('rate', 0):.1f} STB/day",
            f"Injection Pressure: {params.get('pressure', 0):.1f} psi",
            f"WAG Ratio: {params.get('WAG_ratio', 1.0):.2f}",
            f"Recovery Factor: {metrics.get('recovery_factor', 0):.4f}",
            f"NPV: ${metrics.get('npv', 0):.0f}",
            f"CO2 Utilization: {metrics.get('co2_utilization', 0):.2f} MSCF/STB"
        ]
        
        return "\n".join(report)