"""
CMG Input File Generator

This module generates CMG GEM input files from our configuration.

NOTE: This module performs NO CALCULATIONS.
Only formats data into CMG .dat file format.
"""

from typing import Dict, Any, List, Optional
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class CMGInputGenerator:
    """
    Generate CMG GEM input file from our configuration.

    This class formats reservoir data, component definitions, and
    operational parameters into the CMG GEM .dat file format.

    NOTE: This class performs NO CALCULATIONS.
    Only formats data into CMG .dat file format.

    Example:
        >>> generator = CMGInputGenerator()
        >>> generator.generate(config, output_path="case.dat")
    """

    def __init__(self):
        """Initialize CMG input generator."""
        pass

    def generate(
        self,
        config: Dict[str, Any],
        output_path: Path
    ) -> None:
        """
        Generate CMG GEM input file.

        Args:
            config: Configuration dictionary with reservoir, EOR, and operational params
            output_path: Path to output .dat file
        """
        lines = []

        # Header section
        lines.extend(self._generate_header(config))

        # Grid dimensions
        lines.extend(self._generate_grid(config))

        # Component properties
        lines.extend(self._generate_components(config))

        # Rock properties
        lines.extend(self._generate_rock_properties(config))

        # Initial conditions
        lines.extend(self._generate_initial_conditions(config))

        # Wells
        lines.extend(self._generate_wells(config))

        # Schedule
        lines.extend(self._generate_schedule(config))

        # Output control
        lines.extend(self._generate_output_control(config))

        # Write to file
        with open(output_path, 'w') as f:
            f.write('\n'.join(lines))

        logger.info(f"CMG input file written to {output_path}")

    def _generate_header(self, config: Dict[str, Any]) -> List[str]:
        """Generate CMG file header."""
        case_name = config.get('case_name', 'Generated_Case')
        return [
            f"-- CMG GEM Input File Generated by CO2 EOR Optimizer",
            f"-- Case: {case_name}",
            "",
            "*TITLE",
            f"  {case_name}",
            "",
        ]

    def _generate_grid(self, config: Dict[str, Any]) -> List[str]:
        """Generate grid definition section."""
        reservoir = config.get('reservoir', {})

        # Default grid dimensions
        nx = reservoir.get('nx', 20)
        ny = reservoir.get('ny', 20)
        nz = reservoir.get('nz', 5)

        dx = reservoir.get('dx', 50.0)  # ft
        dy = reservoir.get('dy', 50.0)  # ft
        dz = reservoir.get('dz', 10.0)  # ft

        top_depth = reservoir.get('top_depth', 8000.0)  # ft

        return [
            "*GRID",
            f"  INC={nx} {ny} {nz}",
            f"  SIZE={dx} {dy} {dz} FT",
            f"  TOPS={top_depth} FT",
            "",
        ]

    def _generate_components(self, config: Dict[str, Any]) -> List[str]:
        """Generate component definition section."""
        reservoir = config.get('reservoir', {})
        eos_model = reservoir.get('eos_model')

        if eos_model is None:
            # Default components for CO2-EOR
            return self._generate_default_components()

        # User-defined components
        component_names = eos_model.get('component_names', [])
        properties = eos_model.get('component_properties', [])

        lines = [
            "*COMPONENTS",
            f"  NCOMP={len(component_names)}",
            ""
        ]

        # Component names
        lines.append("*NAMES")
        for i, name in enumerate(component_names, 1):
            lines.append(f"  '{name}'")
        lines.append("")

        # Component properties
        lines.append("*PROPS")
        for i, name in enumerate(component_names):
            if i < len(properties):
                props = properties[i]
                # [z_i, MW, Tc, Pc, omega]
                mw = props[1]  # g/mol
                tc = props[2]  # K
                pc = props[3] / 100000  # Pa to bar
                omega = props[4]
                lines.append(f"  {name} MW={mw} TC={tc} PC={pc} OMEGA={omega}")
        lines.append("")

        # Binary interaction coefficients
        binary = eos_model.get('binary_interaction_coeffs', [])
        if len(binary) > 0:
            lines.append("*KIJ")
            n = len(component_names)
            for i in range(n):
                for j in range(i + 1, n):
                    if i < len(binary) and j < len(binary[i]):
                        kij = binary[i][j]
                        if kij != 0:
                            lines.append(f"  {component_names[i]} {component_names[j]} {kij:.4f}")
            lines.append("")

        return lines

    def _generate_default_components(self) -> List[str]:
        """Generate default CO2-EOR components."""
        return [
            "*COMPONENTS",
            "  NCOMP=7",
            "",
            "*NAMES",
            "  'CO2' 'C1' 'C2' 'C3' 'C4' 'C5C6' 'C7P'",
            "",
            "*PROPS",
            "  CO2 MW=44.01 TC=304.13 PC=73.76 OMEGA=0.225",
            "  C1 MW=16.04 TC=190.56 PC=45.99 OMEGA=0.011",
            "  C2 MW=30.07 TC=305.32 TC=48.72 OMEGA=0.099",
            "  C3 MW=44.10 TC=369.83 PC=42.48 OMEGA=0.152",
            "  C4 MW=58.12 TC=425.12 PC=37.92 OMEGA=0.201",
            "  C5C6 MW=86.18 TC=507.40 PC=33.69 OMEGA=0.301",
            "  C7P MW=100.00 TC=540.20 PC=27.56 OMEGA=0.350",
            "",
        ]

    def _generate_rock_properties(self, config: Dict[str, Any]) -> List[str]:
        """Generate rock properties section."""
        reservoir = config.get('reservoir', {})

        porosity = reservoir.get('porosity', 0.2)
        perm_x = reservoir.get('permeability_x', 100)  # mD
        perm_y = reservoir.get('permeability_y', 100)
        perm_z = reservoir.get('permeability_z', 10)

        return [
            "*ROCK",
            f"  PORO={porosity}",
            f"  PERMX={perm_x} PERMY={perm_y} PERMZ={perm_z}",
            "",
        ]

    def _generate_initial_conditions(self, config: Dict[str, Any]) -> List[str]:
        """Generate initial conditions section."""
        reservoir = config.get('reservoir', {})
        eor = config.get('eor', {})

        pressure = reservoir.get('initial_pressure', 4000)  # psi
        temperature = reservoir.get('temperature', 150)  # F

        # Initial composition
        eos_model = reservoir.get('eos_model')
        if eos_model and 'component_properties' in eos_model:
            compositions = eos_model['component_properties'][:, 0]  # z_i
        else:
            # Default composition
            compositions = [0.8, 0.1, 0.03, 0.02, 0.02, 0.01, 0.02]

        lines = [
            "*INITIAL",
            f"  PRES={pressure} PSI",
            f"  TEMP={temperature} F",
            "",
            "*COMPOSITION",
        ]

        for i, z in enumerate(compositions):
            lines.append(f"  {i+1} {z:.4f}")

        lines.append("")
        lines.extend(self._generate_equil_region())
        return lines

    def _generate_equil_region(self) -> List[str]:
        """Generate equilibrium region definition."""
        return [
            "*EQUIL",
            "  1 4000 8000 0 0 0 0",
            "",
        ]

    def _generate_wells(self, config: Dict[str, Any]) -> List[str]:
        """Generate well definitions."""
        eor = config.get('eor', {})

        # Default wells: 1 injector, 1 producer
        return [
            "*WELLS",
            "",
            "*WELL",
            "  'INJECTOR' 'INJ'",
            "  10 10 1 10 10 5",
            "  STATUS=OPEN",
            "",
            "*WELL",
            "  'PRODUCER' 'PROD'",
            "  15 15 1 15 15 5",
            "  STATUS=OPEN",
            "",
        ]

    def _generate_schedule(self, config: Dict[str, Any]) -> List[str]:
        """Generate production schedule."""
        eor = config.get('eor', {})
        operational = config.get('operational', {})

        injection_rate = eor.get('injection_rate', 5000)  # MSCF/d
        project_life = operational.get('project_lifetime_years', 15)

        return [
            "*SCHEDULE",
            "",
            "*DATES",
            "  1 1 ! Year 1, Month 1",
            "",
            "*WELLCTL",
            "  'INJECTOR' STATUS=OPEN RATE={injection_rate} MSCF/D",
            "  'PRODUCER' STATUS=OPEN BHP=500 PSI",
            "",
            "*DATES",
            f"  {project_life} 1 ! Year {project_life}",
            "",
            "*WELLCTL",
            "  'INJECTOR' STATUS=CLOSE",
            "  'PRODUCER' STATUS=CLOSE",
            "",
        ]

    def _generate_output_control(self, config: Dict[str, Any]) -> List[str]:
        """Generate output control section."""
        return [
            "*OUTPUT",
            "  FREQ=MONTHLY",
            "",
            "*SUMMARY",
            "  'FOPT' 'FWPT' 'FGPT' 'FWCT' 'FGOR'",
            "  'WIR:INJECTOR' 'WPR:PRODUCER'",
            "  'BPR:15 15 1'",
            "",
            "*END",
            "",
        ]


__all__ = ["CMGInputGenerator"]
